apiVersion: apps/v1
kind: Deployment
metadata:
  name: supervizor
  labels:
    app: supervizor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supervizor-web
  template:
    metadata:
      labels:
        app: supervizor-web
    spec:
      containers:
        - name: supervizor-web
          image: kevinsieverding/supervizor
          ports:
            - containerPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: supervizor-service
spec:
  selector:
    app: supervizor-web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: supervizor-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: supervizor-service
                port:
                  number: 8080
